swagger: "2.0"
info:
  title: Chess API
  description: API description in Markdown.
  version: 1.0.0
host: api.example.com
basePath: /v1
schemes:
  - http
paths:
  api/seeks:
    get:
      summary: Get all availible matches
      description: 
      produces:
        - application/json
      responses:
        200:
          description: OK
    post:
      summary: Add a new game
      description:
      produces:
        - application/json
      responses:
        201:
          description: Created
  api/seeks/{id}: 
    post:
      summary: Accept to play new game
      description:
      produces:
        - application/json
      responses:
        200:
          description: OK
        404:
          description: Not Found
  api/game/{id}:
    get:
      summary: Get current chess game data
      description:
      produces:
        - application/json
      responses:
        200:
          description: OK
        404: 
          description: No Game Data